trigger:
  - develop

pool: selfhosted

steps:  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  
  - task: gitversion/execute@0
  #  inputs:
  #    versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: Bash@3
    displayName: 'Set version number in gradle'
    inputs:
      targetType: 'inline'
      script: echo "$GITVERSIONNUMBER" && ENV["GITVERSION_MAJORMINORPATCH]
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)

