trigger:
  - main

pool: selfhosted

steps:  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  - task: Bash@3
    displayName: 'SourceDirectory'
    inputs:
      targetType: 'inline'
      script: |
        echo $(Build.SourcesDirectory)
        echo "test - $(Build.SourcesDirectory)"
        
  - task: gitversion/execute@0
  #  inputs:
  #    versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: CmdLine@2
    displayName: 'Publish'
    inputs:
      script: |
        bundle exec fastlane test_gitversion
        
  - task: Bash@3
    displayName: 'Determine which apps were updated'
    inputs:
      targetType: 'inline'
      script: |
        $files=$(git diff HEAD HEAD~ --name-only)
        echo "files $files"
        $temp=$files -split ' '
        $count=$temp.Length
        echo "Total changed $count files"
        For ($i=0; $i -lt $temp.Length; $i++)
        {
            $name=$temp[$i]
            echo "this is $name file"
            if ($name -like "app/*")
            {
              Write-Host "app"
            }
            if ($name -like "app2/*")
            {
              Write-Host "app2"
            }
        }
