trigger:
  - main

pool: selfhosted

steps:  
      
  #- task: Powershell@2
  #  displayName: 'buikldvhfgfgd'
  #  inputs:
  #    targetType: 'inline'
  #    script: |
  #      ##vso[task.setvariable variable=Build_SourcesDirectory;]$(Build.SourcesDirectory)\app2"
    
  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
      
  - task: gitversion/execute@0
    displayName: Determine Version
    inputs:
      useConfigFile: true
      configFilePath: 'app2\GitVersion.yml'
      
  - task: CmdLine@2
    displayName: 'Publish'
    inputs:
      script: |
        bundle exec fastlane test_gitversion
        
  - task: Bash@3
    displayName: 'Determine which apps were updated'
    inputs:
      targetType: 'inline'
      script: |
        IFS=' ' read -ra ADDR <<< "$(git diff HEAD HEAD~ --name-only)"
        for i in "${ADDR[@]}"; do
          for reqsubstr in 'app' 'alt' 'str';do
            if [ -z "${i##*$reqsubstr*}" ] ;then
                echo "String '$i' contain substring: '$reqsubstr'."
            else
              echo "String '$i' don't contain substring: '$reqsubstr'."
            fi
          done
        done
