trigger:
  - main

pool: selfhosted

steps:  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo $(Build.SourcesDirectory) 
        
  - task: gitversion/execute@0
  #  inputs:
  #    versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: CmdLine@2
    displayName: 'Publish'
    inputs:
      script: |
        bundle exec fastlane test_gitversion
        
  - task: Bash@3
    displayName: 'Determine which apps were updated'
    inputs:
      targetType: 'inline'
      script: |
        DIFFS="$(git diff HEAD HEAD~ --name-only)"
