trigger:
  - main

pool: selfhosted

steps:  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  - task: Bash@3
    displayName: 'SourceDirectory'
    inputs:
      targetType: 'inline'
      script: |
        $(Build.SourcesDirectory) = "$(Build.SourcesDirectory)/app2"
        echo "test - $(Build.SourcesDirectory)"
        
  - task: gitversion/execute@0
  #  inputs:
  #    versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: CmdLine@2
    displayName: 'Publish'
    inputs:
      script: |
        bundle exec fastlane test_gitversion
        
  - task: Bash@3
    displayName: 'Determine which apps were updated'
    inputs:
      targetType: 'inline'
      script: |
        IFS=';' read -ra ADDR <<< "$(git diff HEAD HEAD~ --name-only)"
        for i in "${ADDR[@]}"; do
          echo "process $i"
        done
