trigger:
  - test

pool:
  vmImage: 'ubuntu-latest'
  
steps:  
  - task: UseGitVersion@5
    displayName: Determine Version Number
    inputs:
      versionSpec: '5.x'
  - task: Bash@3
    displayName: 'Set version number in gradle'
    inputs:
      targetType: 'inline'
      script: sed -i "s/versionName "1.0"/versionName $GITVERSIONNUMBER/g" app/build.gradle
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)
