trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
  
steps:  
  - task: gitversion/execute@0
    inputs:
      versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: Bash@3
    displayName: 'Set version number in gradle'
    inputs:
      targetType: 'inline'
      script: sed -i "s/versionName "1.0"/versionName $GITVERSIONNUMBER/g" app/build.gradle
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)
  - task: Bash@3
    displayName: 'Install fastlane'
    inputs:
      targetType: 'inline'
      script: sudo gem install fastlane
  - task: Bash@3
    displayName: 'Build and make screenshots'
    inputs:
      targetType: 'inline'
      script: fastlane build && fastlane test && fastlane screenshots
  
  - task: Bash@3
    displayName: 'Publish'
    inputs:
      targetType: 'inline'
      script: fastlane deploy_beta

