trigger:
  - main23445

pool: selfhosted

steps:  
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  
  - task: gitversion/execute@0
  #  inputs:
  #    versionSpec: '5.x'
  # - task: UseGitVersion@5
  #   displayName: Determine Version Number
  #   inputs:
  #     versionSpec: '5.x'
  - task: Bash@3
    displayName: 'Set version number in gradle'
    inputs:
      targetType: 'inline'
      script: echo "$GITVERSIONNUMBER" && sed -i "s/versionName "1.0"/versionName $GITVERSIONNUMBER/g" app/build.gradle
    env:
      GITVERSIONNUMBER: $(GitVersion.SemVer)

  - task: Bash@3
    displayName: 'Install rails'
    inputs:
      targetType: 'inline'
      script: gem install rails && rails -v 
  - task: CmdLine@2
    displayName: 'Install bundle'
    inputs:
      script: |
        bundle install

  - task: Bash@3
    displayName: 'Install fastlane'
    inputs:
      targetType: 'inline'
      script: gem install bundler && gem install fastlane
  - task: CmdLine@2
    displayName: 'Create screenshots'
    inputs:
      script: |
        bundle exec fastlane build && bundle exec fastlane test && bundle exec fastlane screenshots
  - task: CmdLine@2
    displayName: 'Publish'
    inputs:
      script: |
        bundle exec fastlane deploy_beta


