trigger: none

pool: selfhosted

resources:
 pipelines:
   - pipeline: my-test-p
     source: gitversion-m2
     trigger: true

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

