trigger: none

pool: selfhosted

resources:
 pipelines:
   - pipeline: my-test-p
     source: \Folder2\gitversion-m
     trigger: true

steps:  
- task: PowerShell@2
  inputs:
    targetType : inline
    script: |
      $loopCounter= 0
      $vars = @{
        "ci-1" = 4
        "ci-2" = 7
      }
      while ($true) {
        if($loopCounter -ge 5) {
          Write-Error "Retries exceeded. There were $loopCounter retries. Stop the CI."
          break
        }
        foreach ($key in $vars.Keys) {
          $url = "https://dev.azure.com/neroz1x/DevOps%20test/_apis/build/builds?definitions=$($vars[$key])&api-version=5.1"
          $connectionToken=$env:SECRET
          $base64AuthInfo= [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$($connectionToken)"))

          $buildPipeline= Invoke-RestMethod -Uri $url -Headers @{authorization = "Basic $base64AuthInfo"} -Method Get
          $BuildStatus= $buildPipeline.value.status | Select-Object -first 1
          $BuildResult= $buildPipeline.value.result | Select-Object -first 1

          Write-Host "status $BuildStatus"
          Write-Host "result $BuildResult"
          if ($BuildStatus -eq "completed" -And $BuildResult -ne "succeeded") { # Consider adding 'partiallySucceeded' status.
            Write-Error "$key is $BuildResult. Stop this run."
            break 2
          }
          elseif ($BuildStatus -ne "completed") {
            Write-Host "$key is $BuildStatus"
            $loopCounter = $loopCounter + 1
            Start-Sleep -Seconds 20
            continue 2
          }
        }
        break
      }
  env:
    SECRET: $(secret)


- task: PowerShell@2
  inputs:
    targetType : inline
    script: |
      Write-Host "There were $loopCounter retries. Stop the CI."
  env:
    SECRET: $(secret)