trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - ${{ variables['app-paths'] }}
pool: selfhosted

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

