trigger: none

pool: selfhosted

resources:
 pipelines:
   - pipeline: my-test-p
     source: \Folder2\gitversion-m
     trigger: true

steps:  
- task: PowerShell@2
  inputs:
   targetType : inline
   script: |
     $url = "https://dev.azure.com/neroz1x/DevOps%20test/_apis/build/builds?definitions=4&api-version=5.1"
     $connectionToken="aaxr6yzn7zd5j7mtfmqcexigcpicj7h2eyliaam7amknlmxwttua"
     $base64AuthInfo= [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes(":$($connectionToken)"))

       $buildPipeline= Invoke-RestMethod -Uri $url -Headers @{authorization = "Bearer $base64AuthInfo"} -Method Get


       $BuildResult= $buildPipeline.value.result | Select-Object -first 1
       
       Write-Host $buildPipeline

       Write-Host This is Build Result: $BuildResult

