trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - $(if eq(true, true), app/**, app2/**)
pool: selfhosted

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

