trigger:
- none

pool: selfhosted

resources:
 pipelines:
   - pipeline:
     source: gitversion-m
     

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

