trigger:
- none

pool: selfhosted

dependsOn:
- pipeline: gitversion-m
  successful: true

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

