trigger:
  template: trigger-template.yml
    parameters:
      branchInclude: master
      scheme: $(scheme)

pool: selfhosted

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

