trigger:
  template:
    path: trigger-template.yml
    parameters:
      branch: ${{ variables.branch }}
      excludePath: ${{ variables.excludePath }}

pool: selfhosted

steps:  
  - task: Powershell@2
    displayName: 'buikldvhfgfgd'
    inputs:
      targetType: 'inline'
      script: |
        echo "I'm alive"

