# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
desc "Build debug and test APK for screenshots"
  lane :build do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :screenshots do
	capture_android_screenshots
  end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

  desc "Deploy a new version to the Google Play"
  lane :deploy_beta do
    gradle(task: "clean assembleRelease")
	gradle(task: 'assemble', 
		build_type: 'Release',
		properties: {
        "android.injected.signing.store.file" => "D:/Android/AndroidTestApp/fastlane/android-key.jks",
        "android.injected.signing.store.password" => "Neroz1x",
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => "Neroz1x",
        })
    upload_to_play_store(track: 'alpha',
		skip_upload_apk: true,
		skip_upload_changelogs: true,
	)
  end
	
  desc "Deploy a new version to the Google Play"
    lane :test_gitversion do
      puts ENV["GITVERSION_MAJORMINORPATCH"]
      ENV["GITVERSION_MAJOR"] = Time.new.year.to_s
      ENV["GITVERSION_MAJORMINORPATCH"]  = "ENV["GITVERSION_MAJOR"].ENV["GITVERSION_MINOR"].ENV["GITVERSION_PATCH"]"
      puts ENV["GITVERSION_MAJOR"]
      puts ENV["GITVERSION_MAJORMINORPATCH"] 
  end
end
